export const CONFIG = {
  CANVAS_WIDTH: 480,
  CANVAS_HEIGHT: 640,
  FPS: 60,

  PLAYER_SPEED: 4,
  PLAYER_LIVES: 3,
  PLAYER_INVINCIBLE_MS: 2000,
  PLAYER_WIDTH: 32,
  PLAYER_HEIGHT: 32,
  PLAYER_HITBOX_SHRINK: 4,

  BULLET_SPEED: 6,
  SHOOT_INTERVAL_MS: 200,

  ENEMY_DOG_SPEED: 2,
  ENEMY_CAT_SPEED: 1.5,
  ENEMY_CAT_BULLET_SPEED: 3,
  ENEMY_SPAWN_INTERVAL_MS: 1000,
  ENEMY_WIDTH: 28,
  ENEMY_HEIGHT: 28,

  BOSS_HP: 60,
  BOSS_SPEED_PHASE1: 1.5,
  BOSS_SPEED_PHASE2: 3,
  BOSS_WIDTH: 64,
  BOSS_HEIGHT: 64,
  BOSS_BULLET_SPEED: 3,
  BOSS_CHARGE_SPEED: 5,
  BOSS_SPAWN_KILL_COUNT: 30,

  POWERUP_DROP_CHANCE: 0.15,
  POWERUP_SPEED: 2,
  POWERUP_WIDTH: 20,
  POWERUP_HEIGHT: 20,

  SCORE_PER_DOG: 100,
  SCORE_PER_CAT: 150,
  SCORE_PER_BOSS: 5000,
};
